### ISSUE TITLE
missing modules

### ISSUE THREAD

**Issue by ardzero** [FadedJayden/AP_MALPorter#1]
![image](https://user-images.githubusercontent.com/60326315/160005239-2cfc529e-b5df-4ef0-a56e-6c7b9a76575b.png)
if you want you can contact me on discord, whichever you prefer
Discord : https://discord.com/users/522340125380706314

**Comment by ballgoesvroomvroom** [comment]
The module seems to be installed to your C: drive, `C:\python39\lib\site-packages` as shown. But the current directory where the script is being run is in the F: drive, `F:\Programming\MAL Site`.

Is it possible to try running the scripts in the C: drive? Not too sure of the cause here.

**Comment by ardzero** [comment]
@ballgoesvroomvroom 
I can try doing that but if it's too much trouble can you contact me on Discord, so it'd be easier to communicate with you if that doesn't work.
or just give me your Discord, I'll add you.

**Comment by ardzero** [comment]
![image](https://user-images.githubusercontent.com/60326315/160194396-8eaecfda-3598-4463-ac4b-d7b62789caa3.png)

**Comment by ballgoesvroomvroom** [comment]
The link you provided didn't work, add me @ FadedJayden#7171

**Comment by ardzero** [comment]
@ballgoesvroomvroom check I sent you a request. 
ID: ! Darkid#1060

**Comment by ballgoesvroomvroom** [comment]
Different drives for the libraries and scripts were the issue.
Running in the same drive did the work.
