### ISSUE TITLE
Getting a error when the anime name "K", is too short. 

### ISSUE THREAD

**Issue by ardzero** [FadedJayden/AP_MALPorter#2]
![image](https://user-images.githubusercontent.com/60326315/160232115-f3edef80-cc22-490f-8a46-5a540ff67f49.png)
![image](https://user-images.githubusercontent.com/60326315/160232123-5229f786-b5b1-4c01-8134-7861f5bbc9d9.png)
it throws a error when it encounters a really short anime name.

**Comment by ballgoesvroomvroom** [comment]
Seems to be limits imposed by MAL's API. 👍
